version: "3"
services: 
    php:
        build: .
        restart: always
        container_name: trescincopimba
        entrypoint: ["tail", "-f", "/dev/null"]
        
        ports: 
            - 3030:3030
            
